upgrade to markshust 42.0.0

diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -1,6 +1,10 @@
 #!/bin/bash
 set -o errexit
 
+MEM=$(docker info | grep "Total Memory" | cut -d':' -f2 | xargs | sed s/GiB//)
+# Docker reports RAM 0.2 less than what it is actually set to
+(( $(echo "$MEM < 5.8" | bc -l) )) && echo "There must be at least 6GB of RAM allocated to Docker to continue." && exit
+
 # shellcheck source=../env/db.env
 source env/db.env
 # shellcheck source=../env/elasticsearch.env
@@ -9,7 +13,6 @@ source env/elasticsearch.env
 source env/magento.env
 # shellcheck source=../env/rabbitmq.env
 source env/rabbitmq.env
-
 
 DOMAIN=${1:-magento.test}
 
@@ -22,7 +25,7 @@ bin/clinotty chmod u+x bin/magento
 rm -rf src && mkdir src
 
 echo "Waiting for connection to Elasticsearch..."
-bin/clinotty timeout 100 bash -c "
+bin/clinotty timeout $ES_HEALTHCHECK_TIMEOUT bash -c "
     until curl --silent --output /dev/null http://$ES_HOST:$ES_PORT/_cat/health?h=st; do
         printf '.'
         sleep 2
@@ -31,12 +34,12 @@ bin/clinotty timeout 100 bash -c "
 
 echo ""
 echo "Waiting for connection to RabbitMQ..."
-rabbitmqi=10
-until [ $rabbitmqi -le 0 ]; do
-    printf '.'
-    (( rabbitmqi-- ))
-    sleep 2
-done
+bin/clinotty timeout $RABBITMQ_HEALTHCHECK_TIMEOUT bash -c "
+    until curl --silent --output /dev/null http://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$RABBITMQ_HOST:$RABBITMQ_MANAGEMENT_PORT/api/aliveness-test/%2F; do
+        printf '.'
+        sleep 2
+    done"
+[ $? != 0 ] && echo "Failed to connect to RabbitMQ" && exit
 
 bin/clinotty bin/magento setup:install \
   --db-host="$MYSQL_HOST" \
@@ -72,7 +75,8 @@ bin/clinotty bin/magento setup:install \
   --search-engine=elasticsearch7 \
   --elasticsearch-host=$ES_HOST \
   --elasticsearch-port=$ES_PORT \
-  --use-rewrites=1
+  --use-rewrites=1 \
+  --no-interaction
 
 echo "Copying files from container to host after install..."
 bin/copyfromcontainer --all
@@ -82,9 +86,6 @@ bin/clinotty bin/magento setup:static-content:deploy -f
 
 echo "Re-indexing with Elasticsearch..."
 bin/clinotty bin/magento indexer:reindex
-
-echo "Install modman and magento extensions..."
-bin/modman
 
 echo "Setting basic URL and generating SSL certificate..."
 bin/setup-domain "${DOMAIN}"
